### ISSUE TITLE
Intel Iris Xe Graphics

### ISSUE THREAD

**Issue by sheji-sm** [macsupermac/ASUS-Redolbook14-1135G7--Hackintosh#1]
Intel Iris Xe Graphics的问题有希望得到解决吗？希望有结果
能分享一下你的EFI文件吗？

**Comment by macsupermac** [comment]
你好，你是中国网友吗？Iris Xe目前只能调用Framebuffer，无法真正调用QE/CI，存在卡顿现象，目前我已经更新到了Sequoia，我会在闲暇之余更新适配此款机型的EFI，谢谢了。有什么建议可以留下。

**Comment by macsupermac** [comment]
> Intel Iris Xe Graphics的问题有希望得到解决吗？希望有结果 能分享一下你的EFI文件吗？

你好，你是中国网友吗？Iris Xe目前只能调用Framebuffer，无法真正调用QE/CI，存在卡顿现象，目前我已经更新到了Sequoia，我会在闲暇之余更新适配此款机型的EFI，谢谢了。有什么建议可以留下。

**Comment by macsupermac** [comment]
详情请关注InsanelyMac上的https://www.insanelymac.com/forum/topic/358305-80-solved-iris-xe-igpu-on-tiger-lake-successfully-loaded-icllp-frambuffer-and-vram-also-recognizes-1536mb-however-some-issues/

**Comment by sheji-sm** [comment]
> > Intel Iris Xe Graphics的问题有希望得到解决吗？希望有结果 能分享一下你的EFI文件吗？
> 
> 你好，你是中国网友吗？Iris Xe目前只能调用Framebuffer，无法真正调用QE/CI，存在卡顿现象，目前我已经更新到了Sequoia，我会在闲暇之余更新适配此款机型的EFI，谢谢了。有什么建议可以留下。

感谢您为此款电脑的黑苹果做出的贡献，我会持续关注你的状态，目前我笔记本还没拿回来。等拿到本后测试。

**Comment by macsupermac** [comment]
> > > Intel Iris Xe Graphics的问题有希望得到解决吗？希望有结果 能分享一下你的EFI文件吗？
> > 
> > 
> > 你好，你是中国网友吗？Iris Xe目前只能调用Framebuffer，无法真正调用QE/CI，存在卡顿现象，目前我已经更新到了Sequoia，我会在闲暇之余更新适配此款机型的EFI，谢谢了。有什么建议可以留下。
> 
> 感谢您为此款电脑的黑苹果做出的贡献，我会持续关注你的状态，目前我笔记本还没拿回来。等拿到本后测试。

这不是我的开发成果，我只是测试罢了。还是不推荐使用11代核显安装黑苹果，可以通过wytmacpc来联系我，vx，谢谢支持
